name: Test Python App

on:
  push:
    branches:
      - '**'  # Запуск при пуше в любую ветку

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Настройка Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          pip install -r requirements.txt  # если есть файл с зависимостями приложения

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: |
          python -m pytest tests